version: "3.9"
services:
  kong:
    container_name: kong
    image: kong:2.8
    restart: unless-stopped
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
      - ${KONG_ADMIN_HTTP_PORT}:8001/tcp
      - ${KONG_ADMIN_HTTPS_PORT}:8444/tcp
    volumes:
      - ./.volumes/kong/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PLUGINS: cors,jwt,prometheus
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
  db:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data
      - ./.volumes/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  auth:
    container_name: gotrue
    build: https://github.com/netlify/gotrue.git#v1.0.1
    depends_on:
      - db
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 8081
      GOTRUE_OPERATOR_TOKEN: ${GOTRUE_OPERATOR_TOKEN}

      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable&search_path=auth

      GOTRUE_SITE_URL: ${GOTRUE_SITE_URL}
      GOTRUE_DISABLE_SIGNUP: ${GOTRUE_DISABLE_SIGNUP}

      GOTRUE_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      GOTRUE_JWT_EXP: ${GOTRUE_JWT_EXP}
      GOTRUE_JWT_AUD: ${GOTRUE_JWT_AUD}
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated # The default group to assign all new users to.

      GOTRUE_EXTERNAL_GOOGLE_ENABLED: ${GOTRUE_EXTERNAL_GOOGLE_ENABLED}
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: ${GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID}
      GOTRUE_EXTERNAL_GOOGLE_SECRET: ${GOTRUE_EXTERNAL_GOOGLE_SECRET}
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: ${GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI}

      GOTRUE_MAILER_AUTOCONFIRM: ${GOTRUE_MAILER_AUTOCONFIRM}
      GOTRUE_SMTP_ADMIN_EMAIL: ${GOTRUE_SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${GOTRUE_SMTP_HOST}
      GOTRUE_SMTP_PORT: ${GOTRUE_SMTP_PORT}
      GOTRUE_SMTP_USER: ${GOTRUE_SMTP_USER}
      GOTRUE_SMTP_PASS: ${GOTRUE_SMTP_PASS}
  main:
    image: vietlach-backend:0.0.1
    build: ../vietlach-backend
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:v9.0.0
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      PGRST_DB_SCHEMAS: public,storage
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
  storage:
    container_name: storage
    build: ../storage-api
    depends_on:
      - db
      - postgrest
    restart: unless-stopped
    environment:
      ANON_KEY: ${STORAGE_ANON_KEY}
      SERVICE_KEY: ${STORAGE_SERVICE_KEY}
      POSTGREST_URL: http://postgrest:3000
      PGRST_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      PGOPTIONS: -c search_path=storage,public
      FILE_SIZE_LIMIT: 52428800
      # TODO: https://github.com/supabase/storage-api/issues/55
      STORAGE_BACKEND: ${STORAGE_BACKEND}
      TENANT_ID: ${STORAGE_TENANT_ID}
      REGION: ${STORAGE_REGION}
      GLOBAL_S3_BUCKET: ${STORAGE_GLOBAL_S3_BUCKET}
      # FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      # - ./.volumes/storage:/var/lib/storage
      - ./.volumes/storage/.aws:/root/.aws
